### ISSUE TITLE
Installing joy-voyager-export on a fresh new project

### ISSUE THREAD

**Issue by frozar** [rxcod9/joy-voyager-export#8]
I provide a [minimal github repository to reproduce this installation error](https://github.com/frozar/joy-voyager-export-issue). The `README.md` on this repository fully describ how to reproduce this error.

In short, when I try to install `joy-voyager-export` on a new Laravel project, I get these errors:
```shell
$ composer require joy/voyager-export
Using version ^1.2 for joy/voyager-export
./composer.json has been updated
Running composer update joy/voyager-export
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires joy/voyager-export ^1.2 -> satisfiable by joy/voyager-export[v1.2.1, ..., v1.2.17].
    - joy/voyager-export[v1.2.1, ..., v1.2.17] require illuminate/support ^7|^8 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require joy/voyager-export:*" to figure out if any version is installable, or "composer require joy/voyager-export:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by rxcod9** [comment]
I believe it is not tested with Laravel 9 yet
I’ll fix that ASAP

**Comment by rxcod9** [comment]
https://github.com/rxcod9/joy-voyager-export-laravel-demo
This should solve your problem

**Comment by rxcod9** [comment]
Try 
```
composer require joy/voyager-export -W
```

**Comment by frozar** [comment]
Thank you, the command : 
```shell
composer require joy/voyager-export -W
```
on [my minimal example repository](https://github.com/frozar/joy-voyager-export-issue) effectively install joy-voyager-export, but I get another issue. I don't see the buttons to do the export of voyager configuration (this is what I expect from this project :smile:). I'll open another issue on this point.
